<section class="register">
    <h2>Login</h2>
    <?php if ($this->error) { ?>
    <p>One or more errors occurred</p>
<?php } ?>

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(null, ['controller' => 'login', 'action' => 'process']));
    $form->setAttribute('method', 'POST');
    $form->get('submit')->setValue('Submit');

    echo $this->form()->openTag($form);
    ?>

    <dl class="zend_form">
        <dt><?= $this->formLabel($form->get('email')) ?></dt>
        <dt><?= $this->formElement($form->get('email')) ?></dt>
        <dt><?= $this->formElementErrors($form->get('email')) ?></dt>

        <dt><?= $this->formLabel($form->get('password')) ?></dt>
        <dt><?= $this->formElement($form->get('password')) ?></dt>
        <dt><?= $this->formElementErrors($form->get('password')) ?></dt>

        <dt><?= $this->formElement($form->get('submit')) ?></dt>
        <dt><?= $this->formElementErrors($form->get('submit')) ?></dt>
    </dl>

    <?= $this->form()->closeTag() ?>
</section>
