<h1>Users</h1>
<table style="border: 1px solid black">
    <?php
    foreach ($this->users as $user) {
        ?>
        <tr style="border: 1px solid black">
            <td style="border: 1px solid black"><?= $user->id; ?></td>
            <td style="border: 1px solid black"><?= $user->name; ?></td>
            <td style="border: 1px solid black"><?= $user->email; ?></td>
            <td style="border: 1px solid black"><?= $user->password; ?></td>
            <td style="border: 1px solid black"><a href="<?= $this->url(null, ['controller' => 'UserManger', 'action' => 'edit', 'id' => $user->id]); ?>">edit</a></td>
            <td style="border: 1px solid black"><a href="<?= $this->url(null, ['controller' => 'UserManger', 'action' => 'delete', 'id' => $user->id]); ?>">delete</a></td>
        </tr>
        <?php
    }
    ?>
</table>
<br>
<a href="<?= $this->url(null, ['controller' => 'UserManger', 'action' => 'add']); ?>">Add user</a>
